[FIX] mrp: fix mrp.bom write method, accessing index of iterable
Issue:

if 'sequence' in vals and self and self[-1].id == self._prefetch_ids[-1]:
TypeError: 'PrefetchX2many' object is not subscriptable

Cause of the issue:
PrefetchX2many object does not have __getitem__ method, only __iter__

closes odoo/odoo#183224

Signed-off-by: William Henrotin (whe) <whe@odoo.com>