[FIX] base: decorate api key create method
Reproduce
---
- tick "Customers can generate API Keys" in settings
- login as portal user
- Connection & Security -> New API key -> give name -> Confirm ->BUG

```
TypeError: APIKeyDescription.create() missing 1 required positional argument: 'vals_list'
```

opw-4385632

closes odoo/odoo#189871

Signed-off-by: Olivier Dony (odo) <odo@odoo.com>