[FIX] stock: prevent error while validating stock move
Currently, an error occurs when validating stock moves without location.

Step to produce:

- Install the 'mrp_subcontracting' module (make a debugger on).
- Create a product, add some quantities, and remove the value of
'Production Location' and 'Inventory Location' from it.
- Click on the 'Bills of Materials' button which is in the breadcrumbs of the
product form view to create a bom of this product, And set a 'BoM Type' as
Subcontracting and add an Administrator as 'Subcontractors'.
- Go to Inventory / Operations / Transfers / Receipts and create a new
'Receipts', add an Administrator as 'Receive From', and add product in
'Operations' which we created bom.
- Open a form view of 'Receive From' (res.partner) and remove value from
'Subcontractor Location' filed which is in the 'Sales & Purchase' tab.
- Again come to receipts form view and try to validate it.

ValueError: Expected singleton: stock.location()

This occurs because the system attempts to get 'location_id' from the stock move
at [1], but it is not available.

Link [1]: https://github.com/odoo/odoo/blob/231952114ae730bb8d4671f4a61f738e8b6dd5b8/addons/stock/models/stock_move.py#L1566

To resolve this issue, add a condition to check if location_id is not available
then use the company's subcontracting location as the default value.

Sentry-6156032937

closes odoo/odoo#191400

X-original-commit: faf1695c8eec3d9e52bb65ba17b8e716a31a48d1
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>
Signed-off-by: Meet Gandhi (mega) <mega@odoo.com>