[FIX] website_forum: fix traceback when user tries to sort website forum posts
Currently, a traceback is occurring when the user tries to sort a website
forum activity.

To reproduce this issue:

1) Install website_forum
2) Open `Forum` in website and tries t sort based on activity

Error:- "AttributeError: 'NoneType' object has no attribute 'groupby'"

Here in website_forum post, the query was passed as None, and because of the
recent changes from the below-mentioned commit, a traceback is occurring
from line[1].

https://github.com/odoo/odoo/blob/0bac60a7085c51ac8cb4f793b013dbea927d180c/addons/website_forum/controllers/website_forum.py#L126

Line[1]:-
https://github.com/odoo/odoo/blob/0bac60a7085c51ac8cb4f793b013dbea927d180c/odoo/models.py#L5614-L5615

Commit:-
https://github.com/odoo/odoo/pull/183925/commits/6b1df3fddedec486bc20010131ea8da566dade32

sentry-6008918989

closes odoo/odoo#184641

Signed-off-by: Adrien Widart (awt) <awt@odoo.com>