[FIX] point_of_sale: prevent TypeError when closing pos session
When the customer tries to close the pos session,
a traceback will appear.

Steps to reproduce the error:
- Go to Point of Sale > Configuration > Payment Methods > Create new >
  In Journal: Bank > Save
- Open a session > Add a product > Payment > select that payment method >
  validate
- Close Register > Now in count, Add such a number so that the difference will
  become negative > Close Register > Proceed Anyway

Error: A traceback appears:
"TypeError: cannot unpack non-iterable bool object"

When the customer closes the pos session, "_apply_diff_on_account_payment_move"
method will be called.
It will call "_get_diff_vals" method.

When "_get_diff_vals" method returns the False,
https://github.com/odoo/odoo/blob/5a390fede312513a5c9b91d2d18d6d0cfdd43750/addons/point_of_sale/models/pos_session.py#L622-L634

So Here, source_vals, dest_vals will be False
https://github.com/odoo/odoo/blob/5a390fede312513a5c9b91d2d18d6d0cfdd43750/addons/point_of_sale/models/pos_session.py#L1094

So, It will lead to the above Traceback.

sentry-5607468115

closes odoo/odoo#173463

Signed-off-by: Vlad Stroia (vlst) <vlst@odoo.com>