[FIX] base: prevent iOS Safari schema parsing issue
Versions
--------
- 16.0+

Steps
-----
For 17.0+:
1. Create a Sale Order for a new contact without phone number;
2. disable online signature;
3. add a deliverable product to the SO;
4. hit "Send by Email";
5. open the sent mail (e.g. via Mailhog);
6. copy the payment link;
7. open in Safari on iOS;
8. pay the sales order.

Issue
-----
> TypeError: Attempted to assign to readonly property.
>   extractFilteredSchemaValuesFromMicroData@https...
>   extractSchemaValuesFromSchemaOrg@https...
>   global code@https...

Cause
-----
`extractFilteredSchemaValuesFromMicroData` is a function internal to iOS
Safari. It is bugged in that it tries to reassign a `const` in some
scenarios where no elements with `itemprop="telephone"` attributes are
found.

Solution
--------
If the contact doesn't have a mobile or phone number, add an empty `div`
with `itemprop="telephone"`.

opw-4072838

closes odoo/odoo#187528

X-original-commit: 95d8ab142a295b239ad2ecf067691edcbb2bf4f9
Signed-off-by: Rémy Voet (ryv) <ryv@odoo.com>
Signed-off-by: Levi Siuzdak <sile@odoo.com>