[FIX] stock: fix label_transfer_template report
Steps to reproduce:
- Create a PDF report for the stock.picking model
- Use the template stock.label_transfer_template_view_pdf.
- When saving the report, the mentioned error occurred.

```py
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
AttributeError: 'stock.picking' object has no attribute 'move_lines'
Template: stock.label_transfer_template_view_pdf
Path: /t/t/div/t[2]/t[2]
Node: <t t-foreach="picking.move_ids" t-as="move"/>
```
- [Ref](https://github.com/odoo/odoo/pull/78732) were move_lines has been renamed to move_ids.
- [Ref](https://github.com/odoo/odoo/pull/80434) were product_uom_qty has been renamed to reserved_uom_qty.

closes odoo/odoo#187856

X-original-commit: df9198dd39ef8230f4ca58ef5aa89264eb13b612
Signed-off-by: Tiffany Chang (tic) <tic@odoo.com>
Signed-off-by: DHARMENDRA PATEL (dhpa) <dhpa@odoo.com>