[FIX] mrp_subcontracting: prevent error when Replenish product
This error occurs when we delete the specific 'Resupply Subcontractor on Order'
route and subsequently attempt to replenish the product.

Steps to reproduce:
- Install the 'stock' and 'mrp_subcontracting' module
- Inventory > Configuration > Settings > Warehouse > Activate Multi-Step Routes
- Go to routes and delete 'Resupply Subcontractor on Order'
- Now go to any product > Click on 'Replenish'

Traceback: AttributeError
'NoneType' object has no attribute 'id'

At [1], this error occurs when we try to access an attribute called 'id' on an
object that is actually None.

This commit will fix the above error by returning the value of 'domains' if the
route is not present in the '_get_allowed_route_domain' method.

[1]: https://github.com/odoo/odoo/blob/731766aa03ad4cf14349169faab3957c710bc002/addons/mrp_subcontracting/wizard/product_replenish.py#L13

sentry-5514962307

closes odoo/odoo#170269

Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>