[FIX] product: Fix validation error in uom
step to reproduce:
1. create a db in 16.0 with appointment and account_payment module
2. create ``User-defined default`` (ir_default): Settings -> Technical -> User-defined Defaults
- Field = Unit of Measure (product.template)
- Default Value (JSON format) = 3 (pick any id that is not in the same category as `uom.product_uom_unit`)
2. upgrade db to 17.0 version below mentioned traceback will
raised because appointment_account_payment is auto install.
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/service/server.py", line 1313, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 114, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 627, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 693, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 613, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 556, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 567, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /home/odoo/src/enterprise/17.0/appointment_account_payment/data/product_data.xml:8
The default Unit of Measure and the purchase Unit of Measure must be in the same category.

View error context:
'-no context-'
```

why this traceback is raised because here in default values
of [``uom_po_id``](https://github.com/odoo/odoo/blob/834e8a8789d1d451f62ae1e841845baf7d3931a4/addons/product/models/product_template.py#L36)
getting default value of uom_id due to that other catefory
uom_id is coming and [validation](https://github.com/odoo/odoo/blob/834e8a8789d1d451f62ae1e841845baf7d3931a4/addons/product/models/product_template.py#L456)
 error raised and db got blocked

opw-4313919
upg-2182151

closes odoo/odoo#187896

X-original-commit: 0656c0ac2d8fc8a76b0c78ed537e2c8a98fb4aed
Signed-off-by: William André (wan) <wan@odoo.com>