[FIX] base: Prevent quick creation of `ir_model_fields`
The problem can be reproduced in two ways
- by finding a view that integrates a many2one on `ir.model.fields` used
without no_create
- manually add the field via studio on any view.

I found a view with the problem: `marketing_campaign_view_form` which
uses the field `unique_field_id` which is defined as such:
``py
    unique_field_id = fields.Many2one(
        ir.model.fields', string='Unique Field',
        compute='_compute_unique_field_id', readonly=False, store=True)
```

To get there:
- Install `marketing_automation`.
- Open the app
- You arrive in the campaigns view
- Create a new record
- Write the name of a field that doesn't exist, like `dkfjl`.
- A dropdown asks you to “Create `dkfjl`”.
- Click on it
- Crash

```
  File “/home/achraf/src/160/odoo/odoo/addons/base/models/ir_model.py”, line 916, in create
    if not vals.get('model'):
AssertionError: missing model name for {'field_description': 'dfasf'}
```

This commit removes the assertion to use `model` returned by `super().create`
so that the web client catches the error and proposes to create the
record with not one field name but all the required fields

opw-4116187

closes odoo/odoo#186690

X-original-commit: a2ad97839c1b6c32a636e8aa30f19f652e8a9905
Signed-off-by: Rémy Voet (ryv) <ryv@odoo.com>
Signed-off-by: Achraf Ben Azzouz (abz) <abz@odoo.com>