[FIX] link_tracker: fix traceback when the creating a link tracker in website
Currently, a traceback is occurring when the user creates a link tracker having
no schema in URL.

To reproduce this issue:

1) Install website_link, email marketing
2) Create a new link tracker with a target URL
3) Now remove the `http://` from the target URL
4) Open website/site/link tracker

Error:- "AttributeError: 'str' object has no attribute 'to_url'"

This is because when the target URL has no `http://` the URL schema
will be an empty string. So it executes the else block in the below line.

https://github.com/odoo/odoo/blob/8a1e6bef82fdaa98c60ef1e3fa519a03206a6788/addons/link_tracker/models/link_tracker.py#L54-L58

Clearly in the else block the value of `tracker.get_base_url()` is the
string, when joining the `url` and `tracker.get_base_url()` it becomes a
string.

which leads to a traceback when `to_url()` is executed from the string.

sentry-5925121505

closes odoo/odoo#183192

X-original-commit: 7a9899ba1c48c2db65c833a320a4bfa867b6b2ea
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>
Signed-off-by: Altaf Shaik (alsh) <alsh@odoo.com>