[FIX] account_payment: prevent error when generate a payment link
Currently, an error occurs when generating a payment link for an invoice without
add an invoice line.

Step to produce:

- Install the 'account_payment' module.
- Create a new invoice, Click on the 'Actions' button, and try to generate a
payment link.

KeyError: 'amount_due'

An error occurs when the system attempts to get the next payment value at [1],
But there is nothing to pay as an invoice line is not available.

Link [1]: https://github.com/odoo/odoo/blob/288d3926c5d011590aa25e9886cfa36377974dd6/addons/account_payment/models/account_move.py#L104-L105

To handle this issue, return an empty dictionary if the invoice line has not
been added.

Sentry-6078809446

closes odoo/odoo#188030

Signed-off-by: Ruben Gomes (rugo) <rugo@odoo.com>