[FIX] mrp: prevent an error when split a backorder of MO's
Currently, an error occurs when splitting a backorder of MO's.

Step to produce:

- Install the 'mrp' module.
- Enable work orders in the settings.
- Create a BOM for a product P with an operation: - OP1: Assembly line 1,
duration 10 minutes.
- Create and confirm an MO for 5 units of P.
- Add a Work Center and Operation in the work order line.
- Set a producing quantity of 2.
- Validate the MO and create a backorder.
- Open a backorder of MO, Select a backorder that is in a confirmed state.
- Click on the 'Action' button to split a backorder into two productions.

TypeError: argument of type 'NoneType' is not iterable

An error occurs because the system retrieves a None value for
'mo_ids_to_backorder' from the context at [1], which is not iterable.
This causes issues as an iterable value is expected.

Link [1]: https://github.com/odoo/odoo/blob/99e2b13416256a0a23a1a619b92873bcfe15b8a9/addons/mrp/models/mrp_production.py#L1846

To resolve this issue, provide an empty list
for 'mo_ids_to_backorder' if the retrieved value is None instead of an iterable.

Sentry-6080156727

closes odoo/odoo#188434

Signed-off-by: Adrien Widart (awt) <awt@odoo.com>