[FIX] mail: no crash on GIF duplicated category name
Before this commit, opening of GIF picker in some languages
like Portuguese could lead to following crash:

```
OwlError: Got duplicate key in t-foreach: #irritado
```

This happens because GIF picker categories come from Tenor
data and there might be duplicated categories. However in code
we use `category.name` for `t-key`, thus there was a crash when
2 categories had the same name.

This commit fixes the issue by using `category_index` instead,
which is the index of category in the global list of categories,
which is necessarily unique for each GIF category.

opw-4319241

closes odoo/odoo#187453

Signed-off-by: Alexandre Kühn (aku) <aku@odoo.com>