[FIX] stock: prevent an error when creating a stock quant
Currently, an error occurs when creating a stock quant (Pick From) in
'Detailed Operations' list view.

Step to produce:

- Install the 'stock' module.
- Go to Inventory / Operations / Transfers / Receipts and create a receipt, add
'Receive From', and also add 'Product' and 'Demand' in Operations.
- Click on 'Validate' then click on 'Return', and open 'Detailed Operations'.
- Now try to create a new stock quant (Pick From) from a list view.

ValueError: Wrong container value 'WH/Stock'

An error occurs when attempting to create or edit a 'picked'(Pick From) in the
list view of 'Detailed Operations' and the system raises a value error at [1] as
'product_id' takes a string instead of an integer in default values.

link[1]: https://github.com/odoo/odoo/blob/259cba71690c500c335a4a2c43e4c606697bc817/odoo/fields.py#L3582-L3583

To resolve the issue, restricted to creating a stock quant from the
'Detailed Operations' list view

sentry-5089715517

closes odoo/odoo#165705

Signed-off-by: Tiffany Chang (tic) <tic@odoo.com>