[FIX] stock_account,purchase_stock: compensate return of fifo product
The value of the returned product may be different from the one
initially received. In such case, the stock accounting may be broken.

To reproduce the issue:
(Need account_accountant)
1. Create an auto-FIFO product category
2. Create a storable product
3. Confirm a PO with 1 @ 10
4. Receive it
5. Confirm a PO with 4 @ 25
6. Receive 1 with backorder
7. Return it
8. On the backorder, receive 4
9. Bill

Error: Looking at the AML of the stock-in account, some lines are
not reconciled and there is a $15 difference between the totald debit
and the total credit.

Step 7, when returning the product, we actually return the one at
$10. Step 8, we then receive 4 products at $25 (hence the difference
of $15). So, back to step 7, when returning the product, we should
also compensate the stock-in account (with the expense one) in case
of a difference.

Let's look at another case: after step 7, the user "returns the
return". In such case, the value of the new receipt is based on the
returned one (see [1]), i.e.: the value of the newly received
product will be $10. In such case, we also need to (1) compensate
the stock-in account and (2) prevent the pdiff process to generate a
pdiff of $15 (otherwise, we would add a value to the received
product, which would go against the logic of [1]).

This commit does not address the behaviour difference between the
two above use cases (-> depending on how the user receives again the
returned product, its value is not the same). This would probably
need a deeper analysis a change, on master.

Note: a third use case does not work either: (step 1-4), PO 1 @ 25,
receive, bill, return, refund.

[1]
https://github.com/odoo/odoo/blob/07464844c69ac3b667adfede0e4e330831819802/addons/purchase_stock/models/stock_move.py#L32-L40
Initially added by 200aac56771fd1ef759f73b277a6808d96ee5f31

OWP-3698324

X-original-commit: 55658e7f43375d7e1af07293e2cd9d1cc4b33883
Part-of: odoo/odoo#162697