[FIX] base: ir.qweb.field.contact handle null value
In case where display_name is null, the widget contact crash
 - AttributeError: 'bool' object has no attribute 'split'

On odoo.com we have around 3K of partner that have name with null value.
So calling so widget Contact on linked res.users will crash since the
display name is False

closes odoo/odoo#155735

Signed-off-by: Rémy Voet (ryv) <ryv@odoo.com>