[FIX] l10n_es_edi_sii: avoid traceback when same bill reference
If we have two bills with the same bill ref and two different partner, one with
NIF and the other without it, the schedule action to process SII response might
fail since the code expect a NIF in the SII reponse when there is not (bill
with partner without NIF).

Technical example:
>>> partner_info # Candidate invoice in odoo
{'IDOtro': {'ID': 'NO_DISPONIBLE', 'IDType': '06', 'CodigoPais': 'ES'}}
>>> respl_partner_info # SII response
{'NIF': '12345678K', 'IDOtro': None}

This causes a rollback and no bills at all are processed in Odoo's side.

Steps to reproduce:
1/ Create a l10n_es company with l10n_es_edi_sii in test mode
2/ Create a bill with a bill reference 10001, some lines (ex: negative lines)
   that will trigger an error from SII and a partner with a NIF
3/ Copy the partner and remove the NIF
4/ Copy the first bill, keep the same bill reference and change the partner to
   copied one
5/ Post both bills
6/ Trigger the schedule action "EDI : Perform web services operations"
=> Traceback with
ValueError: <class 'AttributeError'>: "'NoneType' object has no attribute
'ID'" while evaluating

Now, a default value is set when the key is not found in
respl_partner_info.IDOtro .

opw-4102638

closes odoo/odoo#179551

X-original-commit: ceff055682b161bea982219997c1688ae8c8620f
Signed-off-by: Claire Bretton (clbr) <clbr@odoo.com>
Signed-off-by: Thomas Beckers (tbs) <tbs@odoo.com>