[FIX] l10n_sa_edi: adapt tax calculation recent refactoring
Steps to reproduce
------------------
* install `l10n_sa_edi`
* switch to a Saudi company
* create an invoice and attempt to print it

You should be met with a traceback:
```
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
KeyError: 'id'
Template: l10n_gcc_invoice.arabic_english_invoice
Path: /t/t/div/table/tbody/t[3]/tr/t[1]/td[2]/span
Node: <span class="text-nowrap" t-field="line.l10n_gcc_invoice_tax_amount"/>
```

Cause
-----
The calculation of `l10n_gcc_invoice_tax_amount` relies on code that was
recently refactored, and therefore doesn't work anymore

opw-4243831

closes odoo/odoo#183101

Signed-off-by: Laurent Smet (las) <las@odoo.com>