[FIX] hw_drivers: remove added parameter due to WIoT incompatibility
If a 17.2 database use a windows IoT (in version 17). Then it will
cause issue as the send_to_controller function is called from
the printer drivers in 17.2 which would be missing the mac parameter
as such, the 17 code have to adapt to 17.2 drivers syntax.
This would cause errors such as:
```
websocket: error from callback <function on_message at 0x0000016400FE0540>: send_to_controller() missing 1 required positional argument: 'iot_mac'
odoo.addons.hw_drivers.websocket_client: websocket received an error: send_to_controller() missing 1 required positional argument: 'iot_mac'
```

(and the idea of putting the mac address as a parameter was pretty
bad to start with)

closes odoo/odoo#172736

Signed-off-by: Yaroslav Soroko (yaso) <yaso@odoo.com>