[FIX] l10n_ar, l10n_cl: prevent error when print & send invoice
When the customer tries to print & send an invoice,
a traceback will appear.

Steps to reproduce the error:
- Install "l10n_ar" module
- Switch to "(AR) Exento" company
- Create a tax (Type: Sales) > Advanced Options > Tax Group (VAT 2.5%)
- Create a new invoice > add a product > add that tax > Confirm
- Print & Send > Print & Send

Error: A traceback appears:
"AttributeError:'account.tax' object has no attribute
'_exclude_tax_group_from_tax_totals_summary'"

https://github.com/odoo/odoo/blob/8502e87f4c7543d66c3dc0b12d1260c1d72d05ec/addons/l10n_ar/models/account_move.py#L350

https://github.com/odoo/odoo/blob/8502e87f4c7543d66c3dc0b12d1260c1d72d05ec/addons/l10n_cl/models/account_move.py#L155
Here, "_exclude_tax_group_from_tax_totals_summary" method is used instead of
"_exclude_tax_groups_from_tax_totals_summary" method.
So, it will lead to the above traceback.

sentry-5999534010

closes odoo/odoo#184321

Signed-off-by: Yolann Sabaux (yosa) <yosa@odoo.com>