[FIX] mrp: prevent error when clicking on Done button in WorkOrder
When the customer creates the workorder for MO and clicks on the Done button
without saving the record, a traceback will appear.

Steps to reproduce the error:
- Create one MO > Work Orders > Add a line > Click on Dropdown > Click on Done

Error: A traceback appears:
'IndexError: tuple index out of range'

https://github.com/odoo/odoo/blob/a082495359a2e6a2bf25cc3744eb80fd6899f5d1/addons/mrp/models/mrp_workorder.py#L462
Here, when customer clicks on the Done button without saving the record,
'workorder_ids' will be empty, so it will lead to the above traceback.

https://github.com/odoo/odoo/blob/a082495359a2e6a2bf25cc3744eb80fd6899f5d1/addons/mrp/static/src/components/wo_list_view_dropdown/wo_list_view_dropdown.js#L52-L61
Here, 'ids' is 'false' because the record is not saved yet,
It will call the 'action_mark_as_done' method with 'false' ids,
eventually, it will generate the above traceback.

sentry-5973943945

closes odoo/odoo#184236

X-original-commit: 0f09639dd39bfdca5a2b1771afcc402d4f5a05bc
Signed-off-by: Martin Maes (marm) <marm@odoo.com>
Signed-off-by: Renilkumar Kajavadra (reka) <reka@odoo.com>