[FIX] web: fix traceback when the user download vacrd for partner without name
Currently, a traceback is occurring when the user tries to download a card
for a child parter of type other than contact.

To reproduce this issue:

1) Install 'Contacts'
2) Create a record of 'Contact & Addresses' of type as 'Other Addresses'
   in an existing contact
3) Now open the above-created contact in the list view
4) Select that record and Download the Vcard for that record

Error:- "AttributeError: 'bool' object has no attribute 'replace'"

When the user creates a partner record without a name
and tried to download the Vcard, it led to a traceback.

Because the name was used in the Vcard, which is false in this case.
https://github.com/odoo/odoo/blob/6abe8da981e10f56eb50d07e8c53dcf97422f0c4/addons/web/models/res_partner.py#L30

Note:- Also in the below line,
'/web_enterprise/partner/<model("res.partner"):partner>/vcard' route was
never used anywhere in the odoo except in one testcase which was also introduced
from the same PR through which the above route was added.

This is because of a confusion as Vcard was initially in enterprise and
later shifted to community.

https://github.com/odoo/odoo/blob/6abe8da981e10f56eb50d07e8c53dcf97422f0c4/addons/web/controllers/vcard.py#L16-L17

This commit will resolve this issue by taking the complete name
when the partner failed to give the name.

sentry-5673082917

closes odoo/odoo#176166

Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>