[FIX] stock: fix traceback when  filtering through on hand in quants
A traceback occurs when the user tries to filter stock quants by on-hand.

To reproduce this issue:

1) Install stocks without demo
2) Archive the warehouse
3) open physical Inventory from operations
4) Filter it through `On-Hand` through Toggle Search Panel

Error:-
"AttributeError: 'int' object has no attribute 'startswith'"

When the user archived the warehouse, we get the `domain_loc`
as `[(0, '=', 1)]` at line [2], this is because of no location,
as the location is derived from the warehouse.

If there is no location, it returns three times of`[(0, '=', 1)]` from [1]

[1]
https://github.com/odoo/odoo/blob/9ce9c6d0d815dcf8fd97fdab484872a607579bd5/addons/stock/models/product.py#L309-L310

[2]
https://github.com/odoo/odoo/blob/9ce9c6d0d815dcf8fd97fdab484872a607579bd5/addons/stock/models/stock_quant.py#L240-L241

This leads to the above traceback when `startswith` is used on the
first value of the domain which is an integer.

https://github.com/odoo/odoo/blob/9ce9c6d0d815dcf8fd97fdab484872a607579bd5/addons/stock/models/stock_quant.py#L180-L184

sentry-6016230486

closes odoo/odoo#187246

X-original-commit: 309080b84c4e4dc546cd85eb9c13c387dd3cda46
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>
Signed-off-by: Altaf Shaik (alsh) <alsh@odoo.com>