[FIX] website_sale_comparison: resolve naming conflict
Versions
--------
- 18.0+

Steps
-----
1. Go to eCommerce;
2. go to a product with attributes;
3. open the editor;
4. set specification to display in accordion;
5. enable "Compare" option on Cart.

Issue
-----
> 500: Internal Server Error
> Error while render the template
> TypeError: tuple indices must be integers or slices, not product.public.category
> Template: website_sale_comparison.specifications_table

Cause
-----
The `categories` value set in this template contains an ordered dict
with `product.attribute.category` records as keys, and
`product.template.attribute.line` records as values.

When inserting its logic into the `website_sale` template, its variable
name conflicts with the `categories` value returned by the `WebsiteSale`
controller, which contains `product.public.category` records.

The issue occurs when it tries to use a `product.attribute.category`
record to index a `product.public.category` recordset.

Solution
--------
Rename the `categories` variable to `attrib_categories` in the
`website_sale_comparison` template.

opw-4356669

closes odoo/odoo#190266

Signed-off-by: Levi Siuzdak <sile@odoo.com>