[FIX] hr_holidays: fix onchange `_onchange_date_from`
Issue: Error when the 'date_from' field is left blank.

Cause: When deleting the 'date_from' field, the onchange
'_onchange_date_from' is triggered. It will call the
'_process_accrual_plans' function and report an error as shown below:

first_level_start_date = allocation.date_from +
get_timedelta(first_level.start_count, first_level.start_type)

TypeError: unsupported operand type(s) for +: 'bool' and 'relativedelta'

Solution:
- Check the 'date_from' condition before calling next function
- Handle it only in the onchange because the 'date_from' field is
required

closes odoo/odoo#162730

Signed-off-by: Sofie Gvaladze (sgv) <sgv@odoo.com>